# This workflow will install Python dependencies and run tests

name: Python application

on:
  push:
    branches: [ "main" , "dev"]
    paths-ignore:
      - "doc/**"
      - "**/README.md"

  pull_request:
    branches: [ "main" , "dev"]
    paths-ignore:
      - "doc/**"
      - "**/README.md"

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    env:
      DISPLAY: :0

    defaults:
      run:
        shell: bash -l {0}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          # - macos-latest
          - ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Prepare Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y xvfb x11-xserver-utils
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &

    - name: Enable Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: anaconda-client-env
        auto-activate-base: false
    - name: Test Conda
      run: |
          conda info
          CONDA_DEFAULT_ENV=test_deprl
          conda create --name $CONDA_DEFAULT_ENV python=3.8 -y
          conda activate $CONDA_DEFAULT_ENV

    - name: Install dependencies
      run: |
        conda activate $CONDA_DEFAULT_ENV
        python3 -m pip install --upgrade pip
        pip3 install -e .
        pip3 install -r requirements.txt
        pip3 install myosuite==2.5.0
        pip3 install pytest

    - name: Run Test environment
      run: |
        conda activate $CONDA_DEFAULT_ENV
        python3 -m pytest ./tests/ -s
